
// AUTHENTICATION
export const SIGN_IN = "SIGN_IN";
export const SIGN_OUT = "SIGN_OUT";
export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";
export const AUTH_USER_UPDATE = "AUTH_USER_UPDATE";

// PROFILE DROPDOWN
export const SELECT_PROFILE_DROPDOWN_OPTION = "SELECT_PROFILE_DROPDOWN_OPTION";
export const TOGGLE_PROFILE_DROPDOWN = "TOGGLE_PROFILE_DROPDOWN";
export const SELECT_EXPORT_DROPDOWN_OPTION = "SELECT_EXPORT_DROPDOWN_OPTION";
export const TOGGLE_EXPORT_DROPDOWN = "TOGGLE_EXPORT_DROPDOWN";
export const SELECT_PACKAGE_DETAIL_DROPDOWN_OPTION = "SELECT_PACKAGE_DETAIL_DROPDOWN_OPTION";
export const TOGGLE_PACKAGE_DETAIL_DROPDOWN = "TOGGLE_PACKAGE_DETAIL_DROPDOWN";
export const TOGGLE_TOP_TAGS_DROPDOWN = "TOGGLE_TOP_TAGS_DROPDOWN";
export const SELECT_TOP_TAGS_DROPDOWN_OPTION = "SELECT_TOP_TAGS_DROPDOWN_OPTION";

// Navigation
export const SELECT_NAVIGATION_ITEM = "SELECT_NAVIGATION_ITEM";

// Import
export const UPDATE_FILEINFO = "UPDATE_FILEINFO";
export const UPDATE_PROCESS = "UPDATE_PROCESS";
export const TOGGLE_ERROR = "TOGGLE_ERROR";
export const SET_IMPORT_INITIAL_STATE = "SET_IMPORT_INITIAL_STATE";

// Toaster
export const TOASTER_TOGGLE = "TOASTER_TOGGLE";

//Drawer
export const OPEN_DRAWER = "OPEN_DRAWER";
export const CLOSE_ALL_DRAWER = "CLOSE_ALL_DRAWER";

// Packages
export const PACKAGE_VIEW_SELECT = "PACKAGE_VIEW_SELECT";
export const FETCH_START = "FETCH_START";
export const FETCH_SUCCESS = "FETCH_SUCCESS";
export const FETCH_FAIL = "FETCH_FAIL";
export const UPDATE_PACKAGES = "UPDATE_PACKAGES";
export const PACKAGE_SELECTION = "PACKAGE_SELECTION";
export const SELECTED_PACKAGE_DETAIL = "SELECTED_PACKAGE_DETAIL";
export const SELCTED_PACKAGE_EDIT_MODE = "SELCTED_PACKAGE_EDIT_MODE";
export const SET_INITIAL_STATE = "SET_INITIAL_STATE";
export const TOGGLE_EXPORT_ALL = "TOGGLE_EXPORT_ALL";

// Pagination
export const SELECTED_PAGE = "SELECTED_PAGE";
export const LIMIT_PER_PAGE = "LIMIT_PER_PAGE";
export const SET_PAGE_COUNT = "SET_PAGE_COUNT";
export const SET_PAGINATION_INITIAL_STATE = "SET_PAGINATION_INITIAL_STATE";

// Pagination
export const USER_SELECTED_PAGE = "USER_SELECTED_PAGE";
export const LIMIT_USER_PER_PAGE = "LIMIT_USER_PER_PAGE";
export const SET_USER_PAGE_COUNT = "SET_USER_PAGE_COUNT";
// export const SET_PAGINATION_INITIAL_STATE = "SET_PAGINATION_INITIAL_STATE";

// Filters
export const SET_SEARCH_FILTERS = "SET_SEARCH_FILTERS";
export const SET_SEARCH_CLICK_STATE = "SET_SEARCH_CLICK_STATE";
export const REMOVE_ALL_FILTERS = "REMOVE_ALL_FILTERS";


// User Management
export const UPDATE_SELECTED_USER = "UPDATE_SELECTED_USER";
export const UPDATE_USERS_DRAWERS = "UPDATE_USERS_DRAWERS";

// Tags
export const FETCH_TAG_START = "FETCH_TAG_START";
export const FETCH_TAG_SUCCESS = "FETCH_TAG_SUCCESS";
export const FETCH_TAG_FAIL = "FETCH_TAG_FAIL";
export const UPDATE_TAGS = "UPDATE_TAGS";

// Dashboard
export const UPDATE_COMPARE_TAGS = "UPDATE_COMPARE_TAGS";
export const UPDATE_COMPARISON = "UPDATE_COMPARISON";
export const UPDATE_REDIRECTION_ARRAY = "UPDATE_REDIRECTION_ARRAY";
export const DASHBOARD_INITIAL_STATE = "DASHBOARD_INITIAL_STATE";

//
export const SHOW_MODAL = "SHOW_MODAL";